### **Get Help and Support**

If you are in emotional distress or suicidal crisis and need to speak to a trained counsellor, calling a helpline, crisis line, or suicide hotline offers a great way to be heard and get sound advice. The person who answers is likely to be able to guide you to the right place if they cannot help. You are not alone.

If you know someone who may be at risk of attempting suicide, you can encourage them to reach out to a suicide prevention hotline for help. There are many resources available in your community that can provide assistance and support to those in crisis.

 

### **Suicide Hotlines and Crisis Lines :**

#### **Befrienders**

Befrienders is a not-for-profit organisation that operates internationally and promotes suicide prevention through emotional support and public education. In Malaysia, 9 centres are part of the National Council of Befrienders Malaysia. These centres offer different services and have different contact information and operating hours as follows :

**Kuala Lumpur**

-   Tel: 03-7956 8145

-   E-mail:[sam\@befrienders.org.my](mailto:sam@befrienders.org.my)

-   Operating Hours: 24 hours

**Penang**

-   Tel: 04-281 5161 / 04-281 1108

-   Whatsapp: 6011-5699 7687

-   E-mail: [pat\@befpen.org](mailto:pat@befpen.org)

-   Operating Hours: 3pm -- 12am (midnight)

**Ipoh**

-   Tel: 05-547 7955 / 05-547 7933

-   E-mail: [sam.befriendersipoh\@gmail.com](mailto:sam.befriendersipoh@gmail.com)

-   Operating Hours: 4pm -- 11pm

**Seremban**

-   Tel: 06-632 1772 / 06-632 1773

-   Whatsapp: 6018-969 1772

-   Operating Hours: 7pm -- 10pm

**Melaka**

-   Tel: 06-284 2500 / 06-284 2700 / 06-281 0181

-   Operating Hours: 7pm -- 12am

**Muar**

-   Tel: 06-952 0313

-   E-mail: [sam\@befriendersmuar.org](mailto:sam@befriendersmuar.org)

-   Operating Hours: 8pm -- 11pm

**Johor Bahru**

-   Tel: 07-331 2300

-   E-mail: [sam\@befriendersjb.org](mailto:sam@befriendersjb.org)

-   Operating Hours: 1pm -- 12am (midnight)

**Kota Kinabalu**

-   Tel: 088-255 788 / 088-259 788

-   Whatsapp: 6016-803 6945

-   E-mail: [befrienderskk\@gmail.com](mailto:befrienderskk@gmail.com)

-   Operating Hours: 7pm -- 10pm

**Kuching**

-   Tel: 082-242 800

-   E-mail: [sam\@befrienderskch.org.my](mailto:sam@befrienderskch.org.my)

-   Operating Hours: 6:30pm -- 9:30pm

 

#### **Malaysian Mental Health Association (MMHA)**

Malaysian Mental Health Association provides support via their phone line on any mental health issues. MMHA also has qualified mental health professionals ie. clinical psychologists, and counselors providing psychological support services. Financial subsidies are readily available to ensure that necessary therapy and support are given to anyone who needs it.

-   Tel: 03-2780 6803

-   E-Mail: [admin\@mmha.org.my](mailto:admin@mmha.org.my)

-   Website: <https://mmha.org.my/>

 

#### **Life Line Association Malaysia**

Life Line Association Malaysia offers free consultation services face-to-face, over the phone and through email. Their motto is 'Help is as close as the telephone".

-   Tel: 03-4265799

-   E-Mail: [counselling\@lifeline.org.my](mailto:counselling@lifeline.org.my)

-   Website: <http://lifeline.org.my/cn/>
